### ISSUE TITLE
Local website broken in node 8 and 14

### ISSUE THREAD

**Issue by rickstaa** [philippotto/Piano-Trainer#22]
I tried setting up this project locally but unfortunately, the website is not displaying. After following the instructions in the [README.md](https://github.com/philippotto/Piano-Trainer/blob/master/README.md) I get the following error when running `npm start`:

```npm
Uncaught SyntaxError: Cannot use import statement outside a module
```

Does anybody know with which npm versions this project is working?

### Current system information
**OS:** Ubuntu 18.03
**node version:** 8.17.0 and 14.13.0
**npm version:** 6.13.4 and 6.14.8
**firefox version:** 81.0
**chrome version:** 85.0.4183.121

**Comment by rickstaa** [comment]
Closed due to inactivity.

**Comment by ddugovic** [comment]
Local website is broken in node 14
https://github.com/ddugovic/Piano-Trainer/runs/1325716879?check_suite_focus=true

**Comment by rickstaa** [comment]
@ddugovic Thanks for pointing me into the right direction.

**Comment by ddugovic** [comment]
Glad to help although GitHub Actions automated almost everything; I just had to click my mouse to generate the CI pipeline and click again to see what the error is.

**Comment by rickstaa** [comment]
Closed due to inactivity.

**Comment by coolbluewater** [comment]
@rickstaa / @ddugovic - could you please explain how to get the app running?
I've tried various things, including change the node/npm version, add "type": "module" to package,json, to no avail.

**Comment by ddugovic** [comment]
I claim that it isn't runnable, but if you were to try to run it, you'd do the steps from https://github.com/ddugovic/Piano-Trainer/blob/master/.github/workflows/node.js.yml which seem to be:

```
npm install
npm ci
npm run build --if-present
npm test
npm start
```
